import * as vscode from "vscode";
import { LunaTool } from "../../core/tools/types";
import { safeResolveWorkspacePath, isProbablyBinary } from "../../utils/workspace";

async function readText(path: string): Promise<{ text: string; bytes: number; truncated: boolean }> { const uri = safeResolveWorkspacePath(path); const bytes = await vscode.workspace.fs.readFile(uri); if (isProbablyBinary(bytes)) return { text: "[binary file omitted]", bytes: bytes.length, truncated: false }; let text = Buffer.from(bytes).toString("utf-8"); const max = 20000; const truncated = text.length > max; if (truncated) text = text.slice(0, max) + "\n...(обрезано)"; return { text, bytes: bytes.length, truncated }; }
export function filesystemTools(confirmWriteWithDiff: (relPath: string, content: string) => Promise<boolean>): LunaTool[] { return [
 { definition: { name: "list_directory", description: "Показать список файлов и папок внутри workspace.", category: "read", readonly: true, safeForParallel: true, parameters: { type: "object", properties: { path: { type: "string", description: "Относительный путь, '.' — корень." } }, required: ["path"] } }, async execute(args) { const uri = safeResolveWorkspacePath(String(args.path ?? ".")); const entries = await vscode.workspace.fs.readDirectory(uri); return entries.length ? entries.map(([n,t]) => `${t === vscode.FileType.Directory ? "[dir]" : "[file]"} ${n}`).join("\n") : "(папка пуста)"; } },
 { definition: { name: "read_file", description: "Прочитать текстовый файл с защитой от больших и бинарных файлов.", category: "read", readonly: true, safeForParallel: true, parameters: { type: "object", properties: { path: { type: "string", description: "Относительный путь к файлу." } }, required: ["path"] } }, async execute(args) { const r = await readText(String(args.path ?? "")); return `path: ${args.path}\nbytes: ${r.bytes}\ntruncated: ${r.truncated}\n---\n${r.text}`; } },
 { definition: { name: "read_file_range", description: "Прочитать диапазон строк файла, не загружая весь файл в модель.", category: "read", readonly: true, safeForParallel: true, parameters: { type: "object", properties: { path: { type: "string", description: "Относительный путь." }, startLine: { type: "number", description: "Начальная строка (1-based)." }, endLine: { type: "number", description: "Конечная строка (1-based, включительно)." } }, required: ["path", "startLine", "endLine"] } }, async execute(args) { const r = await readText(String(args.path ?? "")); const start = Math.max(1, Number(args.startLine ?? 1)); const end = Math.max(start, Number(args.endLine ?? start)); return r.text.split(/\r?\n/).slice(start-1,end).map((l,i)=>`${start+i}: ${l}`).join("\n"); } },
 { definition: { name: "read_lines", description: "Прочитать диапазон строк файла.", category: "read", readonly: true, safeForParallel: true, parameters: { type: "object", properties: { path: { type: "string", description: "Относительный путь." }, startLine: { type: "number", description: "Начальная строка." }, endLine: { type: "number", description: "Конечная строка." } }, required: ["path", "startLine", "endLine"] } }, async execute(args) { const r = await readText(String(args.path ?? "")); const start = Math.max(1, Number(args.startLine ?? 1)); const end = Math.max(start, Number(args.endLine ?? start)); return r.text.split(/\r?\n/).slice(start-1,end).map((l,i)=>`${start+i}: ${l}`).join("\n"); } },
 { definition: { name: "write_file", description: "Создать или перезаписать файл после diff и подтверждения.", category: "write", readonly: false, safeForParallel: false, parameters: { type: "object", properties: { path: { type: "string", description: "Путь." }, content: { type: "string", description: "Новое содержимое." } }, required: ["path", "content"] } }, async execute(args) { const p = String(args.path ?? ""); const ok = await confirmWriteWithDiff(p, String(args.content ?? "")); if (!ok) return "Пользователь отклонил запись файла."; const uri = safeResolveWorkspacePath(p); await vscode.workspace.fs.createDirectory(vscode.Uri.file(require("path").dirname(uri.fsPath))); await vscode.workspace.fs.writeFile(uri, Buffer.from(String(args.content ?? ""), "utf-8")); return `Файл записан: ${p}`; } },
 { definition: { name: "create_directory", description: "Создать папку внутри workspace.", category: "write", readonly: false, safeForParallel: false, parameters: { type: "object", properties: { path: { type: "string", description: "Путь папки." } }, required: ["path"] } }, async execute(args, ctx) { const p = String(args.path ?? ""); if (!(await ctx.confirm(`ИИ-агент хочет создать папку: ${p}`))) return "Пользователь отклонил создание папки."; await vscode.workspace.fs.createDirectory(safeResolveWorkspacePath(p)); return `Папка создана: ${p}`; } }
]; }
